version: '3.4'

services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: spring_boot
    ports:
      - "3308:3306"
    expose:
      - 3306
    networks:
      - victor-network
  spring-boot:
    image: victornsto/spring-boot
    working_dir: /
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3306/spring_boot?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    command: mvn spring-boot:run
    depends_on:
      - db
    ports:
      - 80:80
    networks:
      - victor-network
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - victor-network
volumes:
  portainer_data:
networks: 
    victor-network:
        driver: bridge
