server:
  port: 8080
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://spring.io
spring:
  application:
    name: spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  spring.doc:
    paths-to-match: /api/**
    swagger-ui:
      use-root-path: true

