name: Continuous Integration and Delivery

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Application .jar
        working-directory: ./
        run: mvn clean package

      - name: Docker Compose Build
        working-directory: ./
        run: docker compose build

      - name: Push to DockerHub
        run: |
            docker tag ${{ secrets.DOCKER_USERNAME }}/spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/spring-boot:${{ github.run_id }}
            docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot:latest
            docker push ${{ secrets.DOCKER_USERNAME }}/spring-boot:${{ github.run_id }}
